### ISSUE TITLE
잘 모르겠어요, 스타일 :: 스타일 컴포넌트 재사용 어떻게 하나요 ? 

### ISSUE THREAD

**Issue by qhahd78** [LikeLionSCH/9th_Pet_Promotion_Front#24]
import 했더니 오류가 떴어요 살려주세요

**Comment by minsgy** [comment]
- 오류가 뜬 이유는 아마도 `export` 를 해주지 않아서? 오류가 뜬거같아. 이걸 해야 다른 컴포넌트에서 사용 가능.
- `import` 해서 사용하려면 `Component` 단위로 파일을 나누어서 import 해야됌 !
- 단순하게 한 파일에서 만든  `styled.div'';` 컴포넌트를 가져와서 사용하긴 하돼, 역할 별로 파일을 분류 해야함.
> [참고 링크](https://github.com/2minzy/blog_project/blob/main/client/src/components/Footer.js)
- 슬슬 고수 되기 직전이네..,, 쫌 머싰다? 💯
